[package]
name = "pcb-extract"
version.workspace = true
edition = "2021"

[[bin]]
name = "pcb-extract"
path = "src/main.rs"
required-features = ["cli"]

[lib]
name = "pcb_extract"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
clap = { version = "4", features = ["derive"], optional = true }
thiserror = "2"
log = { workspace = true }
env_logger = { version = "0.11", optional = true }
roxmltree = "0.20"
cfb = "0.14"
zip = { version = "2", default-features = false, features = ["deflate"] }
flate2 = { workspace = true }
tar = "0.4.44"
postcard = { version = "1", features = ["alloc"] }

[dev-dependencies]
approx = "0.5.1"

[features]
default = ["cli"]
cli = ["dep:clap", "dep:env_logger"]
